name: card_hash_generator
description: A package to generate card_hash for use in Pagar.me
version: 0.0.1
author: tihrasguinho
homepage: https://github.com/tihrasguinho/card_hash_generator

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  encrypt: ">=5.0.0 <6.0.0"
  dio: ">=4.0.4 <5.0.0"
  pointycastle: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: